### ISSUE TITLE
NPCs doesn't spawn, and plugin disables

### ISSUE THREAD

**Issue by ghost** [Wind-Development/WindSpigot#105]
**Describe the bug**
One of my plugins use citizens for spawning npcs, and when the npc tries to spawn a npc, it gets an error

**Bug on latest**
Yes, 2.1.2

**Errors**
```
java.lang.NullPointerException: Cannot invoke "ga.windpvp.windspigot.WindSpigot.getLagCompensator()" because the return value of "ga.windpvp.windspigot.WindSpigot.getInstance()" is null
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:630) ~[WindSpigot.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:408) ~[WindSpigot.jar:]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:289) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:235) ~[?:?]
```

**Additional context**
Running on Java 17, Windows 11

**Comment by windcolor-dev** [comment]
Can you post your NPC spawn code?

**Comment by ghost** [comment]
https://paste.md-5.net/giyabuvuvu.http

**Comment by kalibrieren** [comment]
#134 should fix this
