### ISSUE TITLE
Random NPE

### ISSUE THREAD

**Issue by vSKAH** [Wind-Development/WindSpigot#112]
**Describe the bug**
Random npe spawn on console logs 

**Bug on latest**
Latest Dev build

**To Reproduce**
Nothing just wait

**Error**

`java.lang.NullPointerException
[20:17:30 WARN]: at java.base/java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:404)
[20:17:30 WARN]: at java.base/java.util.AbstractQueue.add(AbstractQueue.java:95)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.queuePacket(PlayerConnection.java:2663)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:568)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry$1.accept(EntityTrackerEntry.java:247)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry$1.accept(EntityTrackerEntry.java:243)
[20:17:30 WARN]: at me.rastrian.dev.PlayerMap.forEachNearby(PlayerMap.java:89)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry.addNearPlayers(EntityTrackerEntry.java:224)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry.addNearPlayers(EntityTrackerEntry.java:214)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:111)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:74)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:19)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.World.a(World.java:1462)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1078)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1437)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.SpawnerCreature.a(SpawnerCreature.java:228)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:265)
[20:17:30 WARN]: at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:52)
[20:17:30 WARN]: at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:34)
[20:17:30 WARN]: at ga.windpvp.windspigot.world.WorldTickManager.tickWorlds(WorldTickManager.java:47)
[20:17:30 WARN]: at ga.windpvp.windspigot.world.WorldTickManager.tick(WorldTickManager.java:39)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1086)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:450)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:958)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:729)
[20:17:30 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:163)
[20:17:30 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by windcolor-dev** [comment]
The latest commit should have fixed this.
