### ISSUE TITLE
MobAI broken and some errors with wildstacker

### ISSUE THREAD

**Issue by Fredh1000** [Wind-Development/WindSpigot#30]
**Describe the bug**
When the MobAI is disabled the mobs do not take knockbacks in any way and cannot be moved in any way, I don't know if this is a feature, but it is a bit annoying as a thing, on Nacho the mobs take knockbacks and can also be moved with MobAI disabled.
Then an error occurs with WildStacker when I hit any mob with a CrackShot weapon that has a snowball bullet and a speed of 1000.

**Bug on latest**
Yes, it is present in the latest version and also in the dev builds.

**To Reproduce**
For the MobAI problem just turn off the MobAI and hit or try to move a mob, it won't move. (Option required: MobAI disabled) On Nacho (latest) this bug is not present.
For the second problem I used a custom weapon from the crackshot plugin with a speed of 1000 and a snowball bullet (Plugins required: CrackShot e WildStacker) On Nacho (latest) this bug is not present.

**Screenshots**
I have no screenshot, but regarding the error with WildStacker I can safely paste the error here:
[22:01:17 ERROR]: Could not pass event EntityDamageByEntityEvent to WildStacker v3.7.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[WindSpigot.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[WindSpigot.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[WindSpigot.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) [WindSpigot.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [WindSpigot.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:168) [WindSpigot.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:670) [WindSpigot.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:574) [WindSpigot.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:707) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1204) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:788) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:47) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.EntitySnowball.a(SourceFile:30) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:186) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:2033) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1999) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1823) [WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:667) [WindSpigot.jar:]
        at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:47) [WindSpigot.jar:]
        at ga.windpvp.windspigot.async.world.AsyncWorldTicker.run(AsyncWorldTicker.java:18) [WindSpigot.jar:]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: EntityUnstackEvent cannot be triggered asynchronously from inside synchronized code.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[WindSpigot.jar:]
        at com.bgsoftware.wildstacker.utils.events.EventsCaller.callEntityUnstackEvent(EventsCaller.java:80) ~[WildStacker-3.7.0.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedEntity.runUnstack(WStackedEntity.java:305) ~[WildStacker-3.7.0.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.simulateDeath(DeathSimulation.java:100) ~[WildStacker-3.7.0.jar:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntityLastDamage(EntitiesListener.java:239) ~[WildStacker-3.7.0.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor329.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[WindSpigot.jar:]
        ... 22 more

Java version used: Java 17.
WindSpigot version used: WindSpigot-2.1.1.jar released April 23, 2022 on McMarket.

As soon as I encounter further problems, they will be reported. This fork from Nacho has some very good optimizations and I hope to be able to use it.

**Comment by windcolor-dev** [comment]
Disabling mob movement is an intentional part of disabling mob AI, I will probably add configuration to this. As for the WildStacker incompatibility, this seems to be caused by parallel world ticking, I'll try to fix this soon.

**Comment by windcolor-dev** [comment]
Can you check if this is fixed on the latest dev build?

**Comment by Fredh1000** [comment]
However putting a configuration piece to decide whether to disable or enable the knockback of mobs with MobAI disabled would be really useful.

**Comment by windcolor-dev** [comment]
Is mob movement still disabled with mob AI disabled? I believe I made it so that mobs can move with their AI disabled.

**Comment by Fredh1000** [comment]
Now with MobAI disabled the mobs get knockbacks and can also be pushed.
I like.
