### ISSUE TITLE
Compatibility errors with the CustomOreGen plugin

### ISSUE THREAD

**Issue by Fredh1000** [Wind-Development/WindSpigot#34]
**Describe the bug**
This plugin basically serves to make a custom cobblestone generator that makes other blocks spawn instead of cobblestone. The problem WindSpigot has with this plugin isn't actually a bug, as what it does it does, but it clogs the console with this error:
[11:08:30 ERROR]: Could not pass event BlockFromToEvent to CustomOreGen v1.15.26-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[WindSpigot.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[WindSpigot.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[WindSpigot.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[WindSpigot.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.BlockFlowing.b(BlockFlowing.java:158) ~[WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:744) ~[WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:288) ~[WindSpigot.jar:]
        at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:30) ~[WindSpigot.jar:]
        at ga.windpvp.windspigot.async.world.AsyncWorldTicker.run(AsyncWorldTicker.java:18) ~[WindSpigot.jar:]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchFieldError: BLOCK_FIRE_EXTINGUISH
        at xyz.spaceio.customoregen.Events.onFromTo(Events.java:124) ~[CustomOreGen-1.3.32-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor228.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[WindSpigot.jar:]
        ... 12 more

**Bug on latest**
Yes, it also works in dev builds.

**To Reproduce**
Install the plugin in question and make a cobblestone generator.

**Additional context**
On Paper 1.8.8 this problem is not present. On Nacho I honestly have not tested it.

Java version used: Java 17.
WindSpigot version used: WindSpigot build Respect config option for async path searching WindSpigot Build and Upload #200.

**Comment by windcolor-dev** [comment]
After looking through the source, it seems like this plugin is trying to play an invalid sound.

**Comment by windcolor-dev** [comment]
Can you test again on Paper?

**Comment by Fredh1000** [comment]
Actually you are right, the fault could be the plugin that puts a sound name of a modern version in a legacy version like 1.8.8. The bug is also present in Paper 1.8.8, I will ask the plugin devs for fixes.
