### ISSUE TITLE
The KnockBack is broken again

### ISSUE THREAD

**Issue by Fredh1000** [Wind-Development/WindSpigot#35]
**Describe the bug**
The KnockBack is broken again, but this time in a different way:
Whenever I shut down or crash the server the knockback breaks on next boot and becomes unusable with / kb:
[19:18:51 ERROR]: Could not load knockback.yml, please correct your syntax errors
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 8, column 7:
          stop-sprint: true
          ^
expected <block end>, but found BlockMappingStart
 in 'string', line 24, column 9:
            arrow:
            ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[WindSpigot.jar:]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:228) ~[WindSpigot.jar:]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[WindSpigot.jar:]
        at dev.cobblesword.nachospigot.knockback.KnockbackConfig.init(KnockbackConfig.java:36) ~[WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:190) ~[WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[WindSpigot.jar:]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 8, column 7:
          stop-sprint: true
          ^
expected <block end>, but found BlockMappingStart
 in 'string', line 24, column 9:
            arrow:
            ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[WindSpigot.jar:]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[WindSpigot.jar:]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[WindSpigot.jar:]
        ... 6 more
[19:18:51 ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 8, column 7:
          stop-sprint: true
          ^
expected <block end>, but found BlockMappingStart
 in 'string', line 24, column 9:
            arrow:
            ^

        at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[WindSpigot.jar:]
        at dev.cobblesword.nachospigot.knockback.KnockbackConfig.init(KnockbackConfig.java:40) ~[WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:190) ~[WindSpigot.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[WindSpigot.jar:]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Bug on latest**
Yes, the bug is present in the latest dev build.

**To Reproduce**
Just start a server with WindSpigot, crash it or close it and try to start it agai
n, the knockback will not allow you to load the server giving you syntax errors that don't exist.
Even when you start the server for the first time and generate the KnockBack folder for the first time there will be problems: when you log into the server and do / kb it will tell you that there is no knockback profile (although in fact there are) and it will give you the errors as before in console.
![2022-05-17_23 36 37](https://user-images.githubusercontent.com/82319919/168914326-6e8be68a-4679-49c1-a8fe-7f434e77a952.png)

Now I copy and paste the same error that still happens when you hit a mob with a punch or a bullet:
When you punch:
[23:38:55 INFO]: Fredh1000 lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "dev.cobblesword.nachospigot.knockback.KnockbackProfile.getHorizontal()" because "kb" is null
When you hit with a projectile:
[23:39:54 WARN]: Entity threw exception at world_the_end:14.063358170040734,58.54936653723399,75.62057744625734
[23:39:54 WARN]: java.lang.NullPointerException: Cannot invoke "dev.cobblesword.nachospigot.knockback.KnockbackProfile.getSnowballHorizontal()" because "kb" is null
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.EntityLiving.a(EntityLiving.java:970)
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:854)
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:47)
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.EntitySnowball.a(SourceFile:30)
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:188)
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:2066)
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.World.g(World.java:2032)
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1853)
[23:39:54 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:670)
[23:39:54 WARN]:        at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:46)
[23:39:54 WARN]:        at ga.windpvp.windspigot.async.world.AsyncWorldTicker.run(AsyncWorldTicker.java:18)
[23:39:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:39:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:39:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

All settings are those of the previous tests.

**Comment by windcolor-dev** [comment]
Can you send your knockback.yml?

**Comment by windcolor-dev** [comment]
Try deleting knockback.yml and restarting the server.

**Comment by Fredh1000** [comment]
I have already tried to eliminate the knockback.yml and put it back, I always got the same results, only at the first start it went and without working and without the possibility of changing the knockback.
This is my config (the default one):
# This is the knockback configuration file for WindSpigot.
# For configuration info see this: https://github.com/Wind-Development/WindSpigot/wiki/Knockback-Configuration

knockback:
  current: vanilla
  profiles:
    kohi:
      stop-sprint: true
      friction-horizontal: 2.0
      friction-vertical: 2.0
      horizontal: 0.4
      vertical: 0.4
      vertical-max: 0.4
      vertical-min: -1.0
      extra-horizontal: 0.5
      extra-vertical: 0.1
      wtap-extra-horizontal: 0.5
      wtap-extra-vertical: 0.1
      add-horizontal: 0.0
      add-vertical: 0.0
      projectiles:
          horizontal: 0.4
          vertical: 0.4
        arrow:
          horizontal: 0.4
          vertical: 0.4
        pearl:
          horizontal: 0.4
          vertical: 0.4
        snowball:
          horizontal: 0.4
          vertical: 0.4
          horizontal: 0.4
          vertical: 0.4
    windpvp:
      stop-sprint: true
      friction-horizontal: 2.0
      friction-vertical: 2.0
      horizontal: 0.4
      vertical: 0.4
      vertical-max: 0.4
      vertical-min: -1.0
      extra-horizontal: 0.5
      extra-vertical: 0.1
      wtap-extra-horizontal: 0.55
      wtap-extra-vertical: 0.1
      add-horizontal: 0.0
      add-vertical: 0.0
      projectiles:
          horizontal: 0.7
          vertical: 0.4
        arrow:
          horizontal: 0.4
          vertical: 0.4
        pearl:
          horizontal: 0.4
          vertical: 0.4
        snowball:
          horizontal: 0.7
          vertical: 0.4
          horizontal: 0.7
          vertical: 0.4
    vanilla:
      stop-sprint: true
      friction-horizontal: 1.0
      friction-vertical: 1.0
      horizontal: 0.4
      vertical: 0.4
      vertical-max: 0.4
      vertical-min: -1.0
      extra-horizontal: 1.0
      extra-vertical: 1.0
      wtap-extra-horizontal: 1.0
      wtap-extra-vertical: 1.0
      add-horizontal: 0.0
      add-vertical: 0.0
      projectiles:
          horizontal: 0.4
          vertical: 0.4
        arrow:
          horizontal: 0.4
          vertical: 0.4
        pearl:
          horizontal: 0.4
          vertical: 0.4
        snowball:
          horizontal: 0.4
          vertical: 0.4
          horizontal: 0.4
          vertical: 0.4

**Comment by windcolor-dev** [comment]
Seems to be an issue with saving the config, I've reverted some changes and this is fixed on the latest build.
