### ISSUE TITLE
citizens error spam

### ISSUE THREAD

**Issue by Minecon724** [Wind-Development/WindSpigot#37]
**Describe the bug**
```
[06:47:50 INFO]: [Citizens] Exception while updating 93: null.
[06:47:50 WARN]: java.lang.NullPointerException
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:107)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:87)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.PlayerNavigation.a(PlayerNavigation.java:84)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$3.apply(NMSImpl.java:444)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$3.apply(NMSImpl.java:441)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$4.update(NMSImpl.java:495)
[06:47:50 WARN]:        at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:83)
[06:47:50 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:172)
[06:47:50 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:412)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.t_(EntityHumanNPC.java:392)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:2066)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.World.g(World.java:2032)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.tick(NMSImpl.java:1054)
[06:47:50 WARN]:        at net.citizensnpcs.util.NMS.tick(NMS.java:605)
[06:47:50 WARN]:        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:39)
[06:47:50 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
[06:47:50 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:403)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:927)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707)
[06:47:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[06:47:50 INFO]: [Citizens] Exception while updating 93: null.
[06:47:50 WARN]: java.lang.NullPointerException
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:107)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:87)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.PlayerNavigation.a(PlayerNavigation.java:84)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$3.apply(NMSImpl.java:444)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$3.apply(NMSImpl.java:441)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$4.update(NMSImpl.java:495)
[06:47:50 WARN]:        at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:83)
[06:47:50 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:172)
[06:47:50 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:412)
[06:47:50 WARN]:        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.t_(EntityHumanNPC.java:392)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:2066)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.World.g(World.java:2032)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1853)
[06:47:50 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:670)
[06:47:50 WARN]:        at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:46)
[06:47:50 WARN]:        at ga.windpvp.windspigot.async.world.AsyncWorldTicker.run(AsyncWorldTicker.java:18)
[06:47:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[06:47:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[06:47:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Bug on latest**
Is the bug on the latest version of WindSpigot?
yes

**To Reproduce**
1. enter a bot duel on strikepractice

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by windcolor-dev** [comment]
Can you check if the latest dev build fixes it?

**Comment by Minecon724** [comment]
it doesn't, the error is different tho
```
[10:03:39 INFO]: [Citizens] Exception while updating 95: null.
[10:03:39 WARN]: java.lang.NullPointerException
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:107)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:87)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.PlayerNavigation.a(PlayerNavigation.java:84)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$3.apply(NMSImpl.java:444)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$3.apply(NMSImpl.java:441)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$4.update(NMSImpl.java:495)
[10:03:39 WARN]:        at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:83)
[10:03:39 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:172)
[10:03:39 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:412)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.t_(EntityHumanNPC.java:392)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:2066)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.World.g(World.java:2032)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.tick(NMSImpl.java:1054)
[10:03:39 WARN]:        at net.citizensnpcs.util.NMS.tick(NMS.java:605)
[10:03:39 WARN]:        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:39)
[10:03:39 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
[10:03:39 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:403)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:927)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707)
[10:03:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[10:03:39 INFO]: [Citizens] Exception while updating 95: null.
[10:03:39 WARN]: java.lang.NullPointerException
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:107)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:87)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.PlayerNavigation.a(PlayerNavigation.java:84)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$3.apply(NMSImpl.java:444)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$3.apply(NMSImpl.java:441)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl$4.update(NMSImpl.java:495)
[10:03:39 WARN]:        at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:83)
[10:03:39 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:172)
[10:03:39 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:412)
[10:03:39 WARN]:        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.t_(EntityHumanNPC.java:392)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:2066)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.World.g(World.java:2032)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1853)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:670)
[10:03:39 WARN]:        at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:46)
[10:03:39 WARN]:        at ga.windpvp.windspigot.async.world.AsyncWorldTicker.run(AsyncWorldTicker.java:18)
[10:03:39 WARN]:        at ga.windpvp.windspigot.world.WorldTickerManager.tickAsync(WorldTickerManager.java:104)
[10:03:39 WARN]:        at ga.windpvp.windspigot.world.WorldTickerManager.tick(WorldTickerManager.java:76)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:973)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854)
[10:03:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707)
[10:03:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by windcolor-dev** [comment]
I believe the latest dev build fixes it.

**Comment by Minecon724** [comment]
it does :)
but there are still occasional errors, unsure if related: 
```
[10:41:46 WARN]: Entity threw exception at Arenas_1:45.38346604158581,72.70796799243165,33.20435578048405
[10:41:46 WARN]: java.lang.NullPointerException
[10:41:46 WARN]:        at net.minecraft.server.v1_8_R3.EntityPotion.a(EntityPotion.java:132)
[10:41:46 WARN]:        at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:188)
[10:41:46 WARN]:        at net.minecraft.server.v1_8_R3.EntityPotion.tick(EntityPotion.java:83)
[10:41:46 WARN]:        at net.minecraft.server.v1_8_R3.EntityPotion.t_(EntityPotion.java:78)
[10:41:46 WARN]:        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:2066)
[10:41:46 WARN]:        at net.minecraft.server.v1_8_R3.World.g(World.java:2032)
[10:41:46 WARN]:        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1853)
[10:41:46 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:670)
[10:41:46 WARN]:        at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:46)
[10:41:46 WARN]:        at ga.windpvp.windspigot.async.world.AsyncWorldTicker.run(AsyncWorldTicker.java:18)
[10:41:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[10:41:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[10:41:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by windcolor-dev** [comment]
Hmm, this seems to be a separate issue with potions, I'll look into it later.

**Comment by windcolor-dev** [comment]
Can you check if this is fixed on the latest build?

**Comment by Minecon724** [comment]
hello, sorry for the late reply.
im unable to even start my server on the latest build:
```
[07:02:44 INFO]: Loading WindSpigot config from windspigot.yml
[07:02:44 ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Cannot set to an empty path
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[server.jar:]
        at org.bukkit.configuration.MemorySection.set(MemorySection.java:166) ~[server.jar:]
        at org.bukkit.configuration.MemorySection.set(MemorySection.java:196) ~[server.jar:]
        at org.bukkit.configuration.MemoryConfiguration.addDefault(MemoryConfiguration.java:41) ~[server.jar:]
        at ga.windpvp.windspigot.config.WindSpigotConfig.getBoolean(WindSpigotConfig.java:118) ~[server.jar:]
        at ga.windpvp.windspigot.config.WindSpigotConfig.fireEntityExplodeEvent(WindSpigotConfig.java:518) ~[server.jar:]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at ga.windpvp.windspigot.config.WindSpigotConfig.readConfig(WindSpigotConfig.java:102) ~[server.jar:]
        at ga.windpvp.windspigot.config.WindSpigotConfig.init(WindSpigotConfig.java:61) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:193) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[server.jar:]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by FabrisNick** [comment]
> hello, sorry for the late reply. im unable to even start my server on the latest build:
> 
> ```
> [07:02:44 INFO]: Loading WindSpigot config from windspigot.yml
> [07:02:44 ERROR]: Encountered an unexpected exception
> java.lang.IllegalArgumentException: Cannot set to an empty path
>         at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[server.jar:]
>         at org.bukkit.configuration.MemorySection.set(MemorySection.java:166) ~[server.jar:]
>         at org.bukkit.configuration.MemorySection.set(MemorySection.java:196) ~[server.jar:]
>         at org.bukkit.configuration.MemoryConfiguration.addDefault(MemoryConfiguration.java:41) ~[server.jar:]
>         at ga.windpvp.windspigot.config.WindSpigotConfig.getBoolean(WindSpigotConfig.java:118) ~[server.jar:]
>         at ga.windpvp.windspigot.config.WindSpigotConfig.fireEntityExplodeEvent(WindSpigotConfig.java:518) ~[server.jar:]
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
>         at ga.windpvp.windspigot.config.WindSpigotConfig.readConfig(WindSpigotConfig.java:102) ~[server.jar:]
>         at ga.windpvp.windspigot.config.WindSpigotConfig.init(WindSpigotConfig.java:61) ~[server.jar:]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:193) ~[server.jar:]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[server.jar:]
>         at java.lang.Thread.run(Thread.java:829) ~[?:?]
> ```

same

**Comment by ghost** [comment]
@Minecon724 @CoachYT1 fixed by #40 I believe

**Comment by Minecon724** [comment]
yea fixed

**Comment by Minecon724** [comment]
nvm lol

**Comment by 128931** [comment]
he thought

**Comment by Minecon724** [comment]
```
[13:04:30] [Server thread/ERROR]: Could not load windspigot.yml, please correct your syntax errors
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 73, column 13:
          enable: true
                ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[server.jar:]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:228) ~[server.jar:]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[server.jar:]
	at ga.windpvp.windspigot.config.WindSpigotConfig.init(WindSpigotConfig.java:47) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:193) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[server.jar:]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 73, column 13:
          enable: true
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[server.jar:]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[server.jar:]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[server.jar:]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[server.jar:]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[server.jar:]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[server.jar:]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[server.jar:]
	... 6 more
[13:04:30] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 73, column 13:
          enable: true
                ^

	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[server.jar:]
	at ga.windpvp.windspigot.config.WindSpigotConfig.init(WindSpigotConfig.java:51) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:193) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[server.jar:]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 73, column 13:
          enable: true
                ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[server.jar:]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:228) ~[server.jar:]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[server.jar:]
	at ga.windpvp.windspigot.config.WindSpigotConfig.init(WindSpigotConfig.java:47) ~[server.jar:]
	... 3 more
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 73, column 13:
          enable: true
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[server.jar:]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[server.jar:]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[server.jar:]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[server.jar:]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[server.jar:]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[server.jar:]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[server.jar:]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:228) ~[server.jar:]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[server.jar:]
	at ga.windpvp.windspigot.config.WindSpigotConfig.init(WindSpigotConfig.java:47) ~[server.jar:]
	... 3 more
[13:04:30] [Server thread/ERROR]: 	Cause of unexpected exception was
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 73, column 13:
          enable: true
                ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[server.jar:]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:228) ~[server.jar:]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[server.jar:]
	at ga.windpvp.windspigot.config.WindSpigotConfig.init(WindSpigotConfig.java:47) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:193) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[server.jar:]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 73, column 13:
          enable: true
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[server.jar:]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[server.jar:]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[server.jar:]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[server.jar:]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[server.jar:]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[server.jar:]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[server.jar:]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[server.jar:]
	... 6 more
```

**Comment by 128931** [comment]
latest build works perfectly fine for me try rebuilding the windspigot.yml

**Comment by Minecon724** [comment]
```
[13:07:11] [Server thread/INFO]: -------- World Settings For [world] --------
[13:07:11] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at me.elier.nachospigot.config.NachoWorldConfig.getBoolean(NachoWorldConfig.java:38) ~[server.jar:]
	at me.elier.nachospigot.config.NachoWorldConfig.init(NachoWorldConfig.java:21) ~[server.jar:]
	at me.elier.nachospigot.config.NachoWorldConfig.<init>(NachoWorldConfig.java:17) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.World.<init>(World.java:233) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.WorldServer.<init>(WorldServer.java:69) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:295) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:327) ~[server.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[server.jar:]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by ghost** [comment]
> nvm lol

@Minecon724 I think you’ll need to fix your config since it was messed up by the earlier bug, try going to line 73 in your config and see if there’s any problems around there



> [13:07:11] [Server thread/INFO]: -------- World Settings For [world] --------
> [13:07:11] [Server thread/ERROR]: Encountered an unexpected exception
> java.lang.NullPointerException: null
> 	at me.elier.nachospigot.config.NachoWorldConfig.getBoolean(NachoWorldConfig.java:38) ~[server.jar:]
> 	at me.elier.nachospigot.config.NachoWorldConfig.init(NachoWorldConfig.java:21) ~[server.jar:]
> 	at me.elier.nachospigot.config.NachoWorldConfig.<init>(NachoWorldConfig.java:17) ~[server.jar:]
> 	at net.minecraft.server.v1_8_R3.World.<init>(World.java:233) ~[server.jar:]
> 	at net.minecraft.server.v1_8_R3.WorldServer.<init>(WorldServer.java:69) ~[server.jar:]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:295) ~[server.jar:]
> 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:327) ~[server.jar:]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[server.jar:]
> 	at java.lang.Thread.run(Thread.java:829) ~[?:?]

I know why this happens, I’ll PR a fix when I can

**Comment by Minecon724** [comment]
theres a missing line

**Comment by Minecon724** [comment]
not sure what i should put there

**Comment by windcolor-dev** [comment]
I probably messed something up when migrating the NachoSpigot config, try this build: https://github.com/Wind-Development/WindSpigot/actions/runs/2353692248

Just regenerate your windspigot.yml

**Comment by Minecon724** [comment]
latest build is also working
ill check the above mentioned potions later
