### ISSUE TITLE
crash if "improved-hit-detection" is disabled

### ISSUE THREAD

**Issue by Minecon724** [Wind-Development/WindSpigot#58]
```
[14:52:24 INFO]: UUID of player Minecon724 is 0c7295c0-5704-3308-a572-bcaf34787a08
[14:52:24 WARN]: Failed to handle packet for /127.0.0.1:40632
java.lang.NullPointerException: null
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:695) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:649) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:303) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:155) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:68) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.tick(NetworkManager.java:391) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:203) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:983) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[WindSpigot-2.1.2.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
[14:52:24 INFO]: Minecon724 lost connection: Internal server error
[14:52:24 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:571) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1145) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.handleDisconnection(NetworkManager.java:510) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:523) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:200) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:983) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[WindSpigot-2.1.2.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
```

**Comment by ghost** [comment]
This is fixed by 9b1833e681921f75dc0e96b0453680c9aaf9fea0, however this causes another bug which makes improved hit detection always enabled no matter what you set in the config

**Comment by windcolor-dev** [comment]
I don't think that this commit creates a new bug, due to this line of code in the lag compensator class:
```
        if (!WindSpigotConfig.improvedHitDetection) return;
```

**Comment by windcolor-dev** [comment]
Re-downloading the latest stable release should fix this

**Comment by ghost** [comment]
> I don't think that this commit creates a new bug, due to this line of code in the lag compensator class:
> 
> ```
>         if (!WindSpigotConfig.improvedHitDetection) return;
> ```

Oh, I didn’t know
