### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Fredh1000** [Wind-Development/WindSpigot#84]
**Describe the bug**
This issue occur when i start the server and when kill mobs.
The error is repeated many times in the console.

The issue:
[09:22:51] [Server thread/WARN]: Entity threw exception at worldtest:152.5,2.0,-138.5
[09:22:51] [Server thread/WARN]: java.lang.StackOverflowError
[09:22:51] [Server thread/WARN]: 	at java.base/java.util.ArrayList.indexOf(ArrayList.java:286)
[09:22:51] [Server thread/WARN]: 	at java.base/java.util.ArrayList.contains(ArrayList.java:275)
[09:22:51] [Server thread/WARN]:   at ga.windpvp.windspigot.async.pathsearch.AsyncNavigation.offLoadedSearches(AsyncNavigation.java:159)
[09:22:51] [Server thread/WARN]: 	at ga.windpvp.windspigot.async.pathsearch.AsyncNavigation.a(AsyncNavigation.java:104)
[09:22:51] [Server thread/WARN]: 	at ga.windpvp.windspigot.async.pathsearch.AsyncNavigation.a(AsyncNavigation.java:135)
[09:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:86)
[09:22:51] [Server thread/WARN]: 	at ga.windpvp.windspigot.async.pathsearch.AsyncNavigation.a(AsyncNavigation.java:118)
[09:22:51] [Server thread/WARN]: 	at ga.windpvp.windspigot.async.pathsearch.AsyncNavigation.a(AsyncNavigation.java:135)
[09:22:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NavigationAbstract.a(NavigationAbstract.java:86)

**Bug on latest**
Yes, on latest dev build

**Comment by windcolor-dev** [comment]
Should be fixed, although I still recommend using the latest release.
