### ISSUE TITLE
Compatibility plugin no screen death/respawn

### ISSUE THREAD

**Issue by omgloer** [Wind-Development/WindSpigot#88]
Hello, I tested a dozen plugins to deactivate the death / respawn screen but it does not work on windspigot while it works on paper

[15:53:28] [epollEventLoopGroup-3-4/ERROR]: Could not pass event PlayerDeathEvent to No-Death-Screen v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[Spigot.jar:]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[Spigot.jar:]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[Spigot.jar:]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[Spigot.jar:]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[Spigot.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:496) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:487) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:872) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:849) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:562) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1066) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1198) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1710) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:39) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:7) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:203) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:544) ~[Spigot.jar:]
	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:44) ~[Spigot.jar:]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[Spigot.jar:]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.InboundPacketHandler.channelRead(InboundPacketHandler.java:43) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[Spigot.jar:]
	at net.elzorro99.totemfactions.listeners.packets.v1_8_R3$1.channelRead(v1_8_R3.java:44) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[Spigot.jar:]
	at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.channelRead(PacketReader.java:77) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[Spigot.jar:]
	at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.channelRead(PacketReader.java:77) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[Spigot.jar:]
	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.channelRead(BukkitPipelineInjector.java:57) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:39) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[Spigot.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[Spigot.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[Spigot.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Spigot.jar:]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Spigot.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Spigot.jar:]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Spigot.jar:]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[Spigot.jar:]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[Spigot.jar:]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[Spigot.jar:]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[Spigot.jar:]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Spigot.jar:]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Spigot.jar:]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.IllegalArgumentException: The permission nts.work is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:614) ~[Spigot.jar:]
	at me.bukkit.legacy.main.onPlayerDeath(main.java:51) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[Spigot.jar:]

**Comment by ghost** [comment]
> Caused by: java.lang.IllegalArgumentException: The permission nts.work is already defined!

The plugin is trying to define a permission which already exists. Most likely TacoSpigot added an exception to disallow this. Plugins shouldn’t even be defining permissions in events, so this would probably fall under a plugin issue.

**Comment by Venalia-network** [comment]
I will test this but I don't seem to use this :c
