### ISSUE TITLE
Server no start and crash

### ISSUE THREAD

**Issue by omgloer** [Wind-Development/WindSpigot#91]
Hello, i have one error

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: Exception in thread "WindSpigot Parallel World Thread 0" 
[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: net.minecraft.server.v1_8_R3.ReportedException: Exception while updating neighbours

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: 	at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:41)

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: 	at ga.windpvp.windspigot.async.world.AsyncWorldTicker.run(AsyncWorldTicker.java:18)

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: 	at java.base/java.util.HashMap.keysToArray(HashMap.java:952)

[16:42:58] [WindSpigot Parallel World Thread 0/WARN]: 	at java.base/java.util.HashSet.toArray(HashSet.java:367)

**Comment by omgloer** [comment]
[16:49:41] [epollEventLoopGroup-3-2/WARN]: java.lang.IllegalStateException: PacketSendEvent cannot be triggered asynchronously from inside synchronized code.

[16:49:41] [epollEventLoopGroup-3-2/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)

[16:49:41] [epollEventLoopGroup-3-2/WARN]: 	at dev._2lstudios.hamsterapi.handlers.HamsterChannelHandler.write(HamsterChannelHandler.java:33)

[16:49:41] [epollEventLoopGroup-3-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)

[16:49:41] [epollEventLoopGroup-3-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)

[16:49:41] [epollEventLoopGroup-3-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
